### PR TITLE
Add registration, list, and detail pages for the users drones section.

### PR DESCRIPTION
**Pull request by JUhrig**
Moving the country code selection into another ticket since this PR with the new fluent validation was starting to get kinda large.

---
This change is [Reviewable](https://reviewable.io/reviews/juhrig/c-drone/5)

### CODE REVIEW

**Comment by ferricguy10101** [comment]
*[DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs, line 11 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/5#-Kfx8z_4Sv-Gblgq9YSe:-Kfx8z_4Sv-Gblgq9YSf:b-txoops) ([raw file](https://github.com/juhrig/c-drone/blob/2fcd63aa429b818739af23bba1ddcd806302b086/DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs#L11)):*
> ```Smalltalk
>     public class Drone
>     {
>         private const string CANADA_PREFIX = "C";
> ```

this could also be CF for vintage models >> see: https://www.tc.gc.ca/eng/civilaviation/publications/tp11957-chapter4-ident-92.htm

some modellers may want to be era specific and register with vintage markings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Comment by ferricguy10101** [comment]
*[DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs, line 20 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/5#-Kfx9TJQmaMwv0euRhoZ:-Kfx9TJQmaMwv0euRho_:b2gi131) ([raw file](https://github.com/juhrig/c-drone/blob/2fcd63aa429b818739af23bba1ddcd806302b086/DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs#L20)):*
> ```Smalltalk
>         public int Id { get; set; }
> 
>         [MaxLength(4)]
> ```

this max length signifies that the registration markings are 5 letters long after the dash, was the C(F)-DXXX not our starting point?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Comment by JUhrig** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs, line 11 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/5#-Kfx8z_4Sv-Gblgq9YSe:-Kfx9npMtb5nxQnL66Bp:b-plmafi) ([raw file](https://github.com/juhrig/c-drone/blob/2fcd63aa429b818739af23bba1ddcd806302b086/DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs#L11)):*
<details><summary><i>Previously, ferricguy10101 (Darryl Wood) wrote…</i></summary><blockquote>

this could also be CF for vintage models >> see: https://www.tc.gc.ca/eng/civilaviation/publications/tp11957-chapter4-ident-92.htm

some modellers may want to be era specific and register with vintage markings
</blockquote></details>

We can address this in the country drop down have a vintage section.

---

*[DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs, line 20 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/5#-Kfx9TJQmaMwv0euRhoZ:-KfxA-egVifEPByyW-40:bk4n14l) ([raw file](https://github.com/juhrig/c-drone/blob/2fcd63aa429b818739af23bba1ddcd806302b086/DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs#L20)):*
<details><summary><i>Previously, ferricguy10101 (Darryl Wood) wrote…</i></summary><blockquote>

this max length signifies that the registration markings are 5 letters long after the dash, was the C(F)-DXXX not our starting point?
</blockquote></details>

Ill update this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Comment by JUhrig** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs, line 20 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/5#-Kfx9TJQmaMwv0euRhoZ:-KfxBqI3IX-nOZPQDfYS:b-896fix) ([raw file](https://github.com/juhrig/c-drone/blob/2fcd63aa429b818739af23bba1ddcd806302b086/DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs#L20)):*
<details><summary><i>Previously, JUhrig (Julian Uhrig) wrote…</i></summary><blockquote>

Ill update this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Comment by ferricguy10101** [comment]
*[DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs, line 39 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/5#-KfxBlLeeK-ZKRRaeMqQ:-KfxBlLfiqHRqiEnPCai:b-xqk5s2) ([raw file](https://github.com/juhrig/c-drone/blob/2fcd63aa429b818739af23bba1ddcd806302b086/DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs#L39)):*
> ```Smalltalk
>         [Display(Name = "SerialNumber", Description = "Serial number usually found either on the retail box of bottom of the unit.")]
>         public string SerialNumber { get; set; }
> ```

we should type the drones to account for plane/copter as well as account for weight -- any other things? maybe body type for planes? << not sure about that last one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Comment by JUhrig** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs, line 39 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/5#-KfxBlLeeK-ZKRRaeMqQ:-KfyIZWcmnxmbmqNy4ig:btdg9kr) ([raw file](https://github.com/juhrig/c-drone/blob/2fcd63aa429b818739af23bba1ddcd806302b086/DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs#L39)):*
<details><summary><i>Previously, ferricguy10101 (Darryl Wood) wrote…</i></summary><blockquote>

we should type the drones to account for plane/copter as well as account for weight -- any other things? maybe body type for planes? << not sure about that last one.
</blockquote></details>

make a ticket not part of this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Comment by JUhrig** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs, line 39 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/5#-KfxBlLeeK-ZKRRaeMqQ:-KfyIbm4ajFWYfzMjYf3:b-896fix) ([raw file](https://github.com/juhrig/c-drone/blob/2fcd63aa429b818739af23bba1ddcd806302b086/DroneRegistryApp/DroneRegistryApp/Models/DroneViewModels.cs#L39)):*
<details><summary><i>Previously, JUhrig (Julian Uhrig) wrote…</i></summary><blockquote>

make a ticket not part of this PR.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Comment by ferricguy10101** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5#-:-Kg5NESrJJl2m19Rorf9:bnfp4nl)*

**Comment by JUhrig** [comment]
Reviewed 1 of 22 files at r1.
Review status: 1 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Comment by JUhrig** [comment]
Reviewed 11 of 22 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/5)*

**Pull request merged**
