### PR TITLE
Feature/external login support

### PR DESCRIPTION
**Pull request by JUhrig**
Turned out to be a larger PR thanks to needing to update a bunch of the base packages.

Here is what the partial looks like on login and registration pages.
login
register

---
This change is [Reviewable](https://reviewable.io/reviews/juhrig/c-drone/3)

### CODE REVIEW

**Comment by ferricguy10101** [comment]
*[DroneRegistryApp/DroneRegistryApp/Views/Account/Register.cshtml, line 42 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/3#-KfgpXXwfJEMrDw5Wv_y:-KfgpXXxRNdr2yG4DGrT:bsswz3) ([raw file](https://github.com/juhrig/c-drone/blob/8e69ec42778d7976f62b6a5593cfc7ddc4c282ba/DroneRegistryApp/DroneRegistryApp/Views/Account/Register.cshtml#L42)):*
> ```csharp
> 
> <div class="col-md-4">
>     <h4>Use another service to register.</h4>
> ```

or register with:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/3)*

**Comment by ferricguy10101** [comment]
*[DroneRegistryApp/DroneRegistryApp/Views/Account/Login.cshtml, line 55 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/3#-Kfgq1WXH-7TVqjRlNh-:-Kfgq1WXH-7TVqjRlNh0:b-bzz53t) ([raw file](https://github.com/juhrig/c-drone/blob/8e69ec42778d7976f62b6a5593cfc7ddc4c282ba/DroneRegistryApp/DroneRegistryApp/Views/Account/Login.cshtml#L55)):*
> ```csharp
>     </div>
>     <div class="col-md-4">
>         <h4>Use another service to log in.</h4>
> ```

Or Log in with :

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/3)*

**Comment by ferricguy10101** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/3#-:-Kfgqkz_Hfa8EtJ7EuZR:bnfp4nl)*

**Comment by JUhrig** [comment]
Review status: 0 of 47 files reviewed at latest revision, 2 unresolved discussions.

---

*[DroneRegistryApp/DroneRegistryApp/Views/Account/Login.cshtml, line 55 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/3#-Kfgq1WXH-7TVqjRlNh-:-KfgqtCtmftq1bMN4VXq:b-896fix) ([raw file](https://github.com/juhrig/c-drone/blob/8e69ec42778d7976f62b6a5593cfc7ddc4c282ba/DroneRegistryApp/DroneRegistryApp/Views/Account/Login.cshtml#L55)):*
<details><summary><i>Previously, ferricguy10101 (Darryl Wood) wrote…</i></summary><blockquote>

Or Log in with :
</blockquote></details>

Done.

---

*[DroneRegistryApp/DroneRegistryApp/Views/Account/Register.cshtml, line 42 at r1](https://reviewable.io:443/reviews/juhrig/c-drone/3#-KfgpXXwfJEMrDw5Wv_y:-Kfgqu9M0Sgkv0H-7szX:b-896fix) ([raw file](https://github.com/juhrig/c-drone/blob/8e69ec42778d7976f62b6a5593cfc7ddc4c282ba/DroneRegistryApp/DroneRegistryApp/Views/Account/Register.cshtml#L42)):*
<details><summary><i>Previously, ferricguy10101 (Darryl Wood) wrote…</i></summary><blockquote>

or register with:
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/3)*

**Comment by JUhrig** [comment]
Reviewed 47 of 49 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/3)*

**Pull request merged**
