### PR TITLE
Add initial migration support to project

### PR DESCRIPTION
**Pull request by JUhrig**
Adding migrations to the base project before we get to far.

---
This change is [Reviewable](https://reviewable.io/reviews/juhrig/c-drone/4)

### CODE REVIEW

**Comment by ferricguy10101** [comment]
*[a discussion](https://reviewable.io:443/reviews/juhrig/c-drone/4#-Kfn40JNDFe-AygGHXxO:-Kfn40JNDFe-AygGHXxP:bxs3s71) (no related file):*
can you get a walkthrough written up for this? i can't test it until i know how to use it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/4)*

**Comment by ferricguy10101** [comment]
*[a discussion](https://reviewable.io:443/reviews/juhrig/c-drone/4#-Kfn40JNDFe-AygGHXxO:-Kfn4ryKSOoHiOADPxLf:b-dmlnt4) (no related file):*
<details><summary><i>Previously, ferricguy10101 (Darryl Wood) wrote…</i></summary><blockquote>

can you get a walkthrough written up for this? i can't test it until i know how to use it
</blockquote></details>

nvm... 

Tools > NuGet Package Manager > Package Manager Console >  type 'update-database'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/4)*

**Comment by JUhrig** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/juhrig/c-drone/4#-Kfn40JNDFe-AygGHXxO:-KfnDKd6hn41FIqsyjfi:bm84tik) (no related file):*
<details><summary><i>Previously, ferricguy10101 (Darryl Wood) wrote…</i></summary><blockquote>

nvm... 

Tools > NuGet Package Manager > Package Manager Console >  type 'update-database'
</blockquote></details>

you gots it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/4)*

**Comment by ferricguy10101** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/4)*

**Comment by ferricguy10101** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/juhrig/c-drone/4#-:-Kfq46z-_oQVF2ihuYQB:bnfp4nl)*

**Pull request merged**
